
# STAGE ONE VALUES
TOMATO_GROW_STAGE_ONE_AIR_TEMP_LOWER_BOUND = 24
TOMATO_GROW_STAGE_ONE_AIR_TEMP_UPPER_BOUND = 26
TOMATO_GROW_STAGE_ONE_AIR_HUMIDITY_LOWER_BOUND = 75
TOMATO_GROW_STAGE_ONE_AIR_HUMIDITY_UPPER_BOUND = 100
TOMATO_GROW_STAGE_ONE_SOIL_HUMIDITY_LOWER_BOUND = 580
TOMATO_GROW_STAGE_ONE_SOIL_HUMIDITY_UPPER_BOUND = 630


# STAGE TWO VALUES
TOMATO_GROW_STAGE_TWO_AIR_TEMP_LOWER_BOUND = 22
TOMATO_GROW_STAGE_TWO_AIR_TEMP_UPPER_BOUND = 24
TOMATO_GROW_STAGE_TWO_AIR_HUMIDITY_LOWER_BOUND = 70
TOMATO_GROW_STAGE_TWO_AIR_HUMIDITY_UPPER_BOUND = 80
TOMATO_GROW_STAGE_TWO_SOIL_HUMIDITY_LOWER_BOUND = 550
TOMATO_GROW_STAGE_TWO_SOIL_HUMIDITY_UPPER_BOUND = 610

# STAGE THREE VALUES
TOMATO_GROW_STAGE_THREE_AIR_TEMP_LOWER_BOUND = 24
TOMATO_GROW_STAGE_THREE_AIR_TEMP_UPPER_BOUND = 27
TOMATO_GROW_STAGE_THREE_AIR_HUMIDITY_LOWER_BOUND = 60
TOMATO_GROW_STAGE_THREE_AIR_HUMIDITY_UPPER_BOUND = 80
TOMATO_GROW_STAGE_THREE_SOIL_HUMIDITY_LOWER_BOUND = 550
TOMATO_GROW_STAGE_THREE_SOIL_HUMIDITY_UPPER_BOUND = 610


# soil moisture values
SOIL_MOISTURE_COMPLETLEY_DRY = 850
SOIL_MOISTURE_OK = 600
SOIL_MOISTURE_COMPLETLEY_WET = 400


FAN_GPIO_PIN_NUMBER = 22
HEATER_GPIO_PIN_NUMBER = 23
VAPOR_GPIO_PIN_NUMBER = 24
VALVE_GPIO_PIN_NUMBER = 25

GPIO_STATE_HIGH = 1
GPIO_STATE_LOW = 0

TOMATO_GROW_STAGE_ONE = 1
TOMATO_GROW_STAGE_TWO = 2
TOMATO_GROW_STAGE_THREE = 3
TOMATO_GROW_STAGE_FOUR = 4

OPERATION_IS_IN_PROCESS = 1
OPERATION_COMPELETED_SUCESSFULLY = 0
OPERATION_FAILED = -1

TAKE_PHOTO_HOUR = 12
TAKE_PHOTO_MINUTE = 35

INTERVAL_IN_SECOND = 2

ACTIVE_LOW_STATE = "active_low"
ACTIVE_HIGH_STATE = "active_high"

# output csv file header names
AIR_TEMPERATURE = "air_temperature"
AIR_HUMIDITY = "air_humidity"
SOIL_HUMIDITY = "soil_humidity"
TOMATO_GROW_STAGE = "tomato_grow_stage"
MEASURMENT_TIMESTAMP = "measurment_timestamp"

OUTPUT_CSV_FILENAME = "/home/captainhb/greenhouse_project/modules/environment_parameters.csv"

# camera related paramters
output_photo_dir_name = "/home/captainhb/greenhouse_project/modules/tomato_pics"